info:
  namespace: prod-template
  name: template-api
  image: ghcr.io/template/template-api
  tag: v1.0.0
  imagePullSecrets: dockerconfigjson-github-com
  replicas: 1
  port: 80
  healthCheckPath: "/health"
resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m
ingress:
  host: api.template.com
  path: "/template(/|$)(.*)"
  certManager: letsencrypt-template
extraEnv:
  SERVICE_VERSION: v2
